language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t kkkkmd/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true kkkkmd/react-test-app npm test

after_success:
  - docker build -t kkkkmd/docker-frontend ./frontend
  - docker build -t kkkkmd/docker-backend ./backend
  - docker build -t kkkkmd/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push kkkkmd/docker-frontend
  - docker push kkkkmd/docker-backend
  - docker push kkkkmd/docker-nginx